---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-xml
      - id: check-toml
      - id: pretty-format-json
        args: [--autofix]
      - id: check-json
      - id: check-executables-have-shebangs

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.27.1
    hooks:
      - id: yamllint

  - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
    rev: 0.2.2
    hooks:
      - id: yamlfmt
        args: [--mapping, '2', --sequence, '4', --offset, '2']

  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.17
    hooks:
      - id: helmlint
      - id: shellcheck
      - id: terraform-fmt
      - id: terragrunt-hclfmt
      - id: terraform-validate

  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.2.0
    hooks:
      - id: gitleaks

  - repo: https://github.com/ambv/black
    rev: 22.6.0
    hooks:
      - id: black

  - repo: https://github.com/google/go-jsonnet
    rev: v0.18.0
    hooks:
      - id: jsonnet-format
      - id: jsonnet-lint
